### ISSUE TITLE
im the getting error from login(im updated client to v53)

### ISSUE THREAD

**Issue by acerdevs** [PeterHackz/BrawlStars-Client#7]
PS C:\Users\User\Downloads\BrawlStars-Client-main> node .
[INFO] succesfully connected to game.brawlstarsgame.com:9339
[INFO] sent message of type: 10100, length: 72
[INFO] received message of type: 20103, length: 297925, version: 11
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at module.exports.process (C:\Users\User\Downloads\BrawlStars-Client-main\Messaging\Messages\Server\LoginFailedMessage.js:18:18)
    at Messaging.update (C:\Users\User\Downloads\BrawlStars-Client-main\Messaging\Messaging.js:41:21)
    at Socket.<anonymous> (C:\Users\User\Downloads\BrawlStars-Client-main\TcpSocket\Connection.js:13:23)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v19.0.1
PS C:\Users\User\Downloads\BrawlStars-Client-main>

**Comment by acerdevs** [comment]
PS C:\Users\User\Downloads\BrawlStars-Client-main> node .
[INFO] succesfully connected to game.brawlstarsgame.com:9339
[INFO] sent message of type: 10100, length: 72
[INFO] received message of type: 20103, length: 297925, version: 11
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at module.exports.process (C:\Users\User\Downloads\BrawlStars-Client-main\Messaging\Messages\Server\LoginFailedMessage.js:18:18)
    at Messaging.update (C:\Users\User\Downloads\BrawlStars-Client-main\Messaging\Messaging.js:41:21)
    at Socket.<anonymous> (C:\Users\User\Downloads\BrawlStars-Client-main\TcpSocket\Connection.js:13:23)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v19.0.1
PS C:\Users\User\Downloads\BrawlStars-Client-main>

**Comment by kravetsone** [comment]
> fixed with update fringerprint to 53.176



> fixed with update fringerprint to 53.176



> fixed with update fringerprint to 53.176

Do you have the keys?
